DROP TABLE IF EXISTS SecureFile;
DROP TABLE IF EXISTS SuperSecret;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS FileSharing;
DROP TABLE IF EXISTS SecretSharing;
DROP TABLE IF EXISTS SecretFileCount;
DROP TABLE IF EXISTS SecretPasswordCount;
